Point Cloud Library (PCL): pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT > Class Template Reference
pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT > Class Template Reference
Module keypoints
Keypoint detector for detecting corners in 3D (XYZ), 2D (intensity) AND mixed versions of these.
#include <pcl/keypoints/harris_6d.h>
Public Types
using Ptr = shared_ptr< HarrisKeypoint6D< PointInT, PointOutT, NormalT > >
using ConstPtr = shared_ptr< const HarrisKeypoint6D< PointInT, PointOutT, NormalT > >
using PointCloudIn = typename Keypoint< PointInT, PointOutT >::PointCloudIn
using PointCloudOut = typename Keypoint< PointInT, PointOutT >::PointCloudOut
using KdTree = typename Keypoint< PointInT, PointOutT >::KdTree
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
Public Types inherited from pcl::Keypoint< PointInT, PointOutT >
using Ptr = shared_ptr< Keypoint< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Keypoint< PointInT, PointOutT > >
using BaseClass = PCLBase< PointInT >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(int, double, std::vector< int > &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, int index, double, std::vector< int > &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
HarrisKeypoint6D (float radius=0.01, float threshold=0.0)
Constructor.
virtual ~HarrisKeypoint6D ()
Empty destructor.
void setRadius (float radius)
set the radius for normal estimation and non maxima supression.
void setThreshold (float threshold)
set the threshold value for detecting corners.
void setNonMaxSupression (bool=false)
whether non maxima suppression should be applied or the response for each point should be returned
void setRefine (bool do_refine)
whether the detected key points should be refined or not.
virtual void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to the input dataset that we need to estimate features at every point for.
void setNumberOfThreads (unsigned int nr_threads=0)
Initialize the scheduler and set the number of threads to use.
Public Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
Keypoint ()
void harrisCorner (ImageType &output, ImageType &input, const float sigma_d, const float sigma_i, const float alpha, const float thresh)
void hessianBlob (ImageType &output, ImageType &input, const float sigma, bool SCALE)
void hessianBlob (ImageType &output, ImageType &input, const float start_scale, const float scaling_factor, const int num_scales)
void imageElementMultiply (ImageType &output, ImageType &input1, ImageType &input2)
Keypoint ()
Empty constructor.
~Keypoint ()
Empty destructor.
PointCloudInConstPtr getSearchSurface ()
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod ()
Get a pointer to the search method used.
double getSearchParameter ()
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch ()
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the key point detection.
double getRadiusSearch ()
Get the sphere radius used for determining the neighbors.
pcl::PointIndicesConstPtr getKeypointsIndices ()
void compute (PointCloudOut &output)
Base method for key point detection for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
int searchForNeighbors (int index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void detectKeypoints (PointCloudOut &output)
void responseTomasi (PointCloudOut &output) const
void refineCorners (PointCloudOut &corners) const
void calculateCombinedCovar (const std::vector< int > &neighbors, float *coefficients) const
Protected Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
virtual bool initCompute ()
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual void detectKeypoints (PointCloudOut &output)=0
Abstract key point detection method.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Keypoint< PointInT, PointOutT >
std::string name_
The key point detection method's name.
SearchMethod search_method_
The search method template for indices.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (casted from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
pcl::PointIndicesPtr keypoints_indices_
Indices of the keypoints in the input cloud.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT, typename NormalT = pcl::Normal>
class pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >
Keypoint detector for detecting corners in 3D (XYZ), 2D (intensity) AND mixed versions of these.
Author
Suat Gedikli
Definition at line 49 of file harris_6d.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> using pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::ConstPtr = shared_ptr<const HarrisKeypoint6D<PointInT, PointOutT, NormalT> >
Definition at line 53 of file harris_6d.h.
KdTree
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> using pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::KdTree = typename Keypoint<PointInT, PointOutT>::KdTree
Definition at line 57 of file harris_6d.h.
PointCloudIn
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> using pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::PointCloudIn = typename Keypoint<PointInT, PointOutT>::PointCloudIn
Definition at line 55 of file harris_6d.h.
PointCloudInConstPtr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> using pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::PointCloudInConstPtr = typename PointCloudIn::ConstPtr
Definition at line 58 of file harris_6d.h.
PointCloudOut
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> using pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::PointCloudOut = typename Keypoint<PointInT, PointOutT>::PointCloudOut
Definition at line 56 of file harris_6d.h.
Ptr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> using pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::Ptr = shared_ptr<HarrisKeypoint6D<PointInT, PointOutT, NormalT> >
Definition at line 52 of file harris_6d.h.
Constructor & Destructor Documentation
HarrisKeypoint6D()
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::HarrisKeypoint6D (float radius = 0.01, float threshold = 0.0) inline
Constructor.
Parameters
radius the radius for normal estimation as well as for non maxima suppression
threshold the threshold to filter out weak corners
Definition at line 75 of file harris_6d.h.
References pcl::Keypoint< PointInT, PointOutT >::name_, and pcl::Keypoint< PointInT, PointOutT >::search_radius_.
~HarrisKeypoint6D()
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> virtual pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::~HarrisKeypoint6D () inline virtual
Empty destructor.
Definition at line 88 of file harris_6d.h.
References pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNonMaxSupression(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setRadius(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setRefine(), and pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setThreshold().
Member Function Documentation
calculateCombinedCovar()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::calculateCombinedCovar (const std::vector< int > & neighbors, float * coefficients) const protected
Definition at line 76 of file harris_6d.hpp.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNumberOfThreads().
detectKeypoints()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints (PointCloudOut & output) protected
Definition at line 143 of file harris_6d.hpp.
References pcl::Feature< PointInT, PointOutT >::compute(), pcl::copyPointCloud(), pcl::PointCloud< PointT >::is_dense, pcl::isFinite(), pcl::PointCloud< PointT >::points, pcl::PointCloud< PointT >::resize(), pcl::PCLBase< PointInT >::setInputCloud(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::setInputNormals(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalEstimationMethod(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalSmoothingSize(), pcl::Feature< PointInT, PointOutT >::setRadiusSearch(), and pcl::PointCloud< PointT >::size().
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNumberOfThreads().
refineCorners()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::refineCorners (PointCloudOut & corners) const protected
Definition at line 361 of file harris_6d.hpp.
References pcl::search::KdTree< PointT, Tree >::radiusSearch(), and pcl::search::KdTree< PointT, Tree >::setInputCloud().
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNumberOfThreads().
responseTomasi()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::responseTomasi (PointCloudOut & output) const protected
Definition at line 270 of file harris_6d.hpp.
References pcl::isFinite().
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNumberOfThreads().
setNonMaxSupression()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNonMaxSupression (bool nonmax = false)
whether non maxima suppression should be applied or the response for each point should be returned
Note
this value needs to be turned on in order to apply thresholding and refinement
Parameters
nonmax default is false
Definition at line 69 of file harris_6d.hpp.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::~HarrisKeypoint6D().
setNumberOfThreads()
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setNumberOfThreads (unsigned int nr_threads = 0) inline
Initialize the scheduler and set the number of threads to use.
Parameters
nr_threads the number of hardware threads to use (0 sets the value back to automatic)
Definition at line 124 of file harris_6d.h.
References pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::calculateCombinedCovar(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::refineCorners(), and pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::responseTomasi().
setRadius()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setRadius (float radius)
set the radius for normal estimation and non maxima supression.
Parameters
radius
Definition at line 57 of file harris_6d.hpp.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::~HarrisKeypoint6D().
setRefine()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setRefine (bool do_refine)
whether the detected key points should be refined or not.
If turned of, the key points are a subset of the original point cloud. Otherwise the key points may be arbitrary. note non maxima supression needs to be on in order to use this feature.
Parameters
do_refine
Definition at line 63 of file harris_6d.hpp.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::~HarrisKeypoint6D().
setSearchSurface()
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> virtual void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setSearchSurface (const PointCloudInConstPtr & cloud) inline virtual
Provide a pointer to the input dataset that we need to estimate features at every point for.
Parameters
cloud the const boost shared pointer to a PointCloud message
Reimplemented from pcl::Keypoint< PointInT, PointOutT >.
Definition at line 118 of file harris_6d.h.
References pcl::PointCloud< PointT >::clear(), and pcl::Keypoint< PointInT, PointOutT >::surface_.
setThreshold()
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::setThreshold (float threshold)
set the threshold value for detecting corners.
This is only evaluated if non maxima suppression is turned on. note non maxima suppression needs to be activated in order to use this feature.
Parameters
threshold
Definition at line 51 of file harris_6d.hpp.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::~HarrisKeypoint6D().
The documentation for this class was generated from the following files:
pcl/keypoints/harris_6d.h
pcl/keypoints/impl/harris_6d.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Sun Mar 8 2020 12:52:16