Point Cloud Library (PCL): pcl::SampleConsensusModelRegistration2D< PointT > Class Template Reference
pcl::SampleConsensusModelRegistration2D< PointT > Class Template Reference
Module sample_consensus
SampleConsensusModelRegistration2D defines a model for Point-To-Point registration outlier rejection using distances between 2D pixels.
#include <pcl/sample_consensus/sac_model_registration_2d.h>
Public Types
using PointCloud = typename pcl::SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename pcl::SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename pcl::SampleConsensusModel< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< SampleConsensusModelRegistration2D< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModelRegistration2D< PointT > >
Public Types inherited from pcl::SampleConsensusModelRegistration< PointT >
using PointCloud = typename SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename SampleConsensusModel< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< SampleConsensusModelRegistration< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModelRegistration< PointT > >
Public Types inherited from pcl::SampleConsensusModel< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointCloudPtr = typename PointCloud::Ptr
using SearchPtr = typename pcl::search::Search< PointT >::Ptr
using Ptr = shared_ptr< SampleConsensusModel< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModel< PointT > >
Public Member Functions
SampleConsensusModelRegistration2D (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelRegistration2D.
SampleConsensusModelRegistration2D (const PointCloudConstPtr &cloud, const std::vector< int > &indices, bool random=false)
Constructor for base SampleConsensusModelRegistration2D.
virtual ~SampleConsensusModelRegistration2D ()
Empty destructor.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const
Compute all distances from the transformed points to their correspondences.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, std::vector< int > &inliers)
Select all the points which respect the given model coefficients as inliers.
virtual std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const
Count all the points which respect the given model coefficients as inliers.
void setProjectionMatrix (const Eigen::Matrix3f &projection_matrix)
Set the camera projection matrix.
Eigen::Matrix3f getProjectionMatrix () const
Get the camera projection matrix.
Public Member Functions inherited from pcl::SampleConsensusModelRegistration< PointT >
SampleConsensusModelRegistration (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelRegistration.
SampleConsensusModelRegistration (const PointCloudConstPtr &cloud, const std::vector< int > &indices, bool random=false)
Constructor for base SampleConsensusModelRegistration.
~SampleConsensusModelRegistration ()
Empty destructor.
void setInputCloud (const PointCloudConstPtr &cloud) override
Provide a pointer to the input dataset.
void setInputTarget (const PointCloudConstPtr &target)
Set the input point cloud target.
void setInputTarget (const PointCloudConstPtr &target, const std::vector< int > &indices_tgt)
Set the input point cloud target.
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXf &model_coefficients) const override
Compute a 4x4 rigid transformation matrix from the samples given.
void optimizeModelCoefficients (const std::vector< int > &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const override
Recompute the 4x4 transformation using the given inlier set.
void projectPoints (const std::vector< int > &, const Eigen::VectorXf &, PointCloud &, bool=true) const override
Create a new point cloud with inliers projected onto the model.
bool doSamplesVerifyModel (const std::set< int > &, const Eigen::VectorXf &, const double) const override
Verify whether a subset of indices verifies a given set of model coefficients.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_REGISTRATION).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const std::vector< int > &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, std::vector< int > &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const std::vector< int > &indices)
Provide the vector of indices that represents the input data.
IndicesPtr getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Protected Member Functions
bool isSampleGood (const std::vector< int > &samples) const
Check if a sample of indices results in a good sample of points indices.
void computeSampleDistanceThreshold (const PointCloudConstPtr &)
Computes an "optimal" sample distance threshold based on the principal directions of the input cloud.
void computeSampleDistanceThreshold (const PointCloudConstPtr &, const std::vector< int > &)
Computes an "optimal" sample distance threshold based on the principal directions of the input cloud.
Protected Member Functions inherited from pcl::SampleConsensusModelRegistration< PointT >
void computeSampleDistanceThreshold (const PointCloudConstPtr &cloud)
Computes an "optimal" sample distance threshold based on the principal directions of the input cloud.
void computeSampleDistanceThreshold (const PointCloudConstPtr &cloud, const std::vector< int > &indices)
Computes an "optimal" sample distance threshold based on the principal directions of the input cloud.
void estimateRigidTransformationSVD (const pcl::PointCloud< PointT > &cloud_src, const std::vector< int > &indices_src, const pcl::PointCloud< PointT > &cloud_tgt, const std::vector< int > &indices_tgt, Eigen::VectorXf &transform) const
Estimate a rigid transformation between a source and a target point cloud using an SVD closed-form solution of absolute orientation using unit quaternions.
void computeOriginalIndexMapping ()
Compute mappings between original indices of the input_/target_ clouds.
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (std::vector< int > &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (std::vector< int > &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
virtual bool isModelValid (const Eigen::VectorXf &model_coefficients) const
Check whether a model is valid given the user constraints.
int rnd ()
Boost-based random number generator.
Additional Inherited Members
Protected Attributes inherited from pcl::SampleConsensusModelRegistration< PointT >
PointCloudConstPtr target_
A boost shared pointer to the target point cloud data array.
IndicesPtr indices_tgt_
A pointer to the vector of target point indices to use.
std::map< int, int > correspondences_
Given the index in the original point cloud, give the matching original index in the target cloud.
double sample_dist_thresh_
Internal distance threshold used for the sample selection step.
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
IndicesPtr indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
std::vector< int > shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
std::shared_ptr< boost::variate_generator< boost::mt19937 &, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT>
class pcl::SampleConsensusModelRegistration2D< PointT >
SampleConsensusModelRegistration2D defines a model for Point-To-Point registration outlier rejection using distances between 2D pixels.
Author
Radu B. Rusu
Definition at line 51 of file sac_model_registration_2d.h.
Member Typedef Documentation
ConstPtr
template<typename PointT> using pcl::SampleConsensusModelRegistration2D< PointT >::ConstPtr = shared_ptr<const SampleConsensusModelRegistration2D<PointT> >
Definition at line 70 of file sac_model_registration_2d.h.
PointCloud
template<typename PointT> using pcl::SampleConsensusModelRegistration2D< PointT >::PointCloud = typename pcl::SampleConsensusModel<PointT>::PointCloud
Definition at line 65 of file sac_model_registration_2d.h.
PointCloudConstPtr
template<typename PointT> using pcl::SampleConsensusModelRegistration2D< PointT >::PointCloudConstPtr = typename pcl::SampleConsensusModel<PointT>::PointCloudConstPtr
Definition at line 67 of file sac_model_registration_2d.h.
PointCloudPtr
template<typename PointT> using pcl::SampleConsensusModelRegistration2D< PointT >::PointCloudPtr = typename pcl::SampleConsensusModel<PointT>::PointCloudPtr
Definition at line 66 of file sac_model_registration_2d.h.
Ptr
template<typename PointT> using pcl::SampleConsensusModelRegistration2D< PointT >::Ptr = shared_ptr<SampleConsensusModelRegistration2D<PointT> >
Definition at line 69 of file sac_model_registration_2d.h.
Constructor & Destructor Documentation
SampleConsensusModelRegistration2D() [1/2]
template<typename PointT> pcl::SampleConsensusModelRegistration2D< PointT >::SampleConsensusModelRegistration2D (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelRegistration2D.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 76 of file sac_model_registration_2d.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, pcl::SampleConsensusModel< PointT >::sample_size_, and pcl::SampleConsensusModelRegistration< PointT >::setInputCloud().
SampleConsensusModelRegistration2D() [2/2]
template<typename PointT> pcl::SampleConsensusModelRegistration2D< PointT >::SampleConsensusModelRegistration2D (const PointCloudConstPtr & cloud, const std::vector< int > & indices, bool random = false) inline
Constructor for base SampleConsensusModelRegistration2D.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 93 of file sac_model_registration_2d.h.
References pcl::SampleConsensusModelRegistration< PointT >::computeOriginalIndexMapping(), pcl::SampleConsensusModelRegistration2D< PointT >::computeSampleDistanceThreshold(), pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
~SampleConsensusModelRegistration2D()
template<typename PointT> virtual pcl::SampleConsensusModelRegistration2D< PointT >::~SampleConsensusModelRegistration2D () inline virtual
Empty destructor.
Definition at line 107 of file sac_model_registration_2d.h.
References pcl::SampleConsensusModelRegistration2D< PointT >::countWithinDistance(), pcl::SampleConsensusModelRegistration2D< PointT >::getDistancesToModel(), and pcl::SampleConsensusModelRegistration2D< PointT >::selectWithinDistance().
Member Function Documentation
computeSampleDistanceThreshold() [1/2]
template<typename PointT> void pcl::SampleConsensusModelRegistration2D< PointT >::computeSampleDistanceThreshold (const PointCloudConstPtr &) inline protected
Computes an "optimal" sample distance threshold based on the principal directions of the input cloud.
Definition at line 164 of file sac_model_registration_2d.h.
Referenced by pcl::SampleConsensusModelRegistration2D< PointT >::SampleConsensusModelRegistration2D().
computeSampleDistanceThreshold() [2/2]
template<typename PointT> void pcl::SampleConsensusModelRegistration2D< PointT >::computeSampleDistanceThreshold (const PointCloudConstPtr & , const std::vector< int > &) inline protected
Computes an "optimal" sample distance threshold based on the principal directions of the input cloud.
Definition at line 191 of file sac_model_registration_2d.h.
References PCL_MAKE_ALIGNED_OPERATOR_NEW.
countWithinDistance()
template<typename PointT > std::size_t pcl::SampleConsensusModelRegistration2D< PointT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Reimplemented from pcl::SampleConsensusModelRegistration< PointT >.
Definition at line 178 of file sac_model_registration_2d.hpp.
Referenced by pcl::SampleConsensusModelRegistration2D< PointT >::~SampleConsensusModelRegistration2D().
getDistancesToModel()
template<typename PointT > void pcl::SampleConsensusModelRegistration2D< PointT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const virtual
Compute all distances from the transformed points to their correspondences.
Parameters
[in] model_coefficients the 4x4 transformation matrix
[out] distances the resultant estimated distances
Reimplemented from pcl::SampleConsensusModelRegistration< PointT >.
Definition at line 64 of file sac_model_registration_2d.hpp.
Referenced by pcl::SampleConsensusModelRegistration2D< PointT >::~SampleConsensusModelRegistration2D().
getProjectionMatrix()
template<typename PointT> Eigen::Matrix3f pcl::SampleConsensusModelRegistration2D< PointT >::getProjectionMatrix () const inline
Get the camera projection matrix.
Definition at line 146 of file sac_model_registration_2d.h.
References pcl::SampleConsensusModelRegistration2D< PointT >::isSampleGood().
isSampleGood()
template<typename PointT > bool pcl::SampleConsensusModelRegistration2D< PointT >::isSampleGood (const std::vector< int > & samples) const protected virtual
Check if a sample of indices results in a good sample of points indices.
Parameters
[in] samples the resultant index samples
Reimplemented from pcl::SampleConsensusModelRegistration< PointT >.
Definition at line 47 of file sac_model_registration_2d.hpp.
Referenced by pcl::SampleConsensusModelRegistration2D< PointT >::getProjectionMatrix().
selectWithinDistance()
template<typename PointT > void pcl::SampleConsensusModelRegistration2D< PointT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, std::vector< int > & inliers) virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the 4x4 transformation matrix
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Reimplemented from pcl::SampleConsensusModelRegistration< PointT >.
Definition at line 116 of file sac_model_registration_2d.hpp.
References pcl::geometry::distance().
Referenced by pcl::SampleConsensusModelRegistration2D< PointT >::~SampleConsensusModelRegistration2D().
setProjectionMatrix()
template<typename PointT> void pcl::SampleConsensusModelRegistration2D< PointT >::setProjectionMatrix (const Eigen::Matrix3f & projection_matrix) inline
Set the camera projection matrix.
Parameters
[in] projection_matrix the camera projection matrix
Definition at line 141 of file sac_model_registration_2d.h.
Referenced by pcl::registration::CorrespondenceRejectorSampleConsensus2D< PointT >::getRemainingCorrespondences().
The documentation for this class was generated from the following files:
pcl/sample_consensus/sac_model_registration_2d.h
pcl/sample_consensus/impl/sac_model_registration_2d.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Sun Mar 8 2020 12:52:58