Point Cloud Library (PCL): pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT > Class Template Reference
pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT > Class Template Reference
Module keypoints
SUSANKeypoint implements a RGB-D extension of the SUSAN detector including normal directions variation in top of intensity variation.
#include <pcl/keypoints/susan.h>
Public Types
using Ptr = shared_ptr< SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT > >
using ConstPtr = shared_ptr< const SUSANKeypoint< PointInT, PointOutT, NormalT, Intensity > >
using PointCloudIn = typename Keypoint< PointInT, PointOutT >::PointCloudIn
using PointCloudOut = typename Keypoint< PointInT, PointOutT >::PointCloudOut
using KdTree = typename Keypoint< PointInT, PointOutT >::KdTree
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudN = pcl::PointCloud< NormalT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
Public Types inherited from pcl::Keypoint< PointInT, PointOutT >
using Ptr = shared_ptr< Keypoint< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Keypoint< PointInT, PointOutT > >
using BaseClass = PCLBase< PointInT >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(int, double, std::vector< int > &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, int index, double, std::vector< int > &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
SUSANKeypoint (float radius=0.01f, float distance_threshold=0.001f, float angular_threshold=0.0001f, float intensity_threshold=7.0f)
Constructor.
~SUSANKeypoint ()
Empty destructor.
void setRadius (float radius)
set the radius for normal estimation and non maxima supression.
void setDistanceThreshold (float distance_threshold)
void setAngularThreshold (float angular_threshold)
set the angular_threshold value for detecting corners.
void setIntensityThreshold (float intensity_threshold)
set the intensity_threshold value for detecting corners.
void setNormals (const PointCloudNConstPtr &normals)
set normals if precalculated normals are available.
void setSearchSurface (const PointCloudInConstPtr &cloud) override
Provide a pointer to the input dataset that we need to estimate features at every point for.
void setNumberOfThreads (unsigned int nr_threads)
Initialize the scheduler and set the number of threads to use.
void setNonMaxSupression (bool nonmax)
Apply non maxima suppression to the responses to keep strongest corners.
void setGeometricValidation (bool validate)
Filetr false positive using geometric criteria.
Public Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
Keypoint ()
void harrisCorner (ImageType &output, ImageType &input, const float sigma_d, const float sigma_i, const float alpha, const float thresh)
void hessianBlob (ImageType &output, ImageType &input, const float sigma, bool SCALE)
void hessianBlob (ImageType &output, ImageType &input, const float start_scale, const float scaling_factor, const int num_scales)
void imageElementMultiply (ImageType &output, ImageType &input1, ImageType &input2)
Keypoint ()
Empty constructor.
~Keypoint ()
Empty destructor.
PointCloudInConstPtr getSearchSurface ()
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod ()
Get a pointer to the search method used.
double getSearchParameter ()
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch ()
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the key point detection.
double getRadiusSearch ()
Get the sphere radius used for determining the neighbors.
pcl::PointIndicesConstPtr getKeypointsIndices ()
void compute (PointCloudOut &output)
Base method for key point detection for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
int searchForNeighbors (int index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute () override
void detectKeypoints (PointCloudOut &output) override
Abstract key point detection method.
bool isWithinNucleusCentroid (const Eigen::Vector3f &nucleus, const Eigen::Vector3f &centroid, const Eigen::Vector3f &nc, const PointInT &point) const
return true if a point lies within the line between the nucleus and the centroid
Protected Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Keypoint< PointInT, PointOutT >
std::string name_
The key point detection method's name.
SearchMethod search_method_
The search method template for indices.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (casted from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
pcl::PointIndicesPtr keypoints_indices_
Indices of the keypoints in the input cloud.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT, typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>>
class pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >
SUSANKeypoint implements a RGB-D extension of the SUSAN detector including normal directions variation in top of intensity variation.
It is different from Harris in that it exploits normals directly so it is faster. Original paper "SUSAN A New Approach to Low Level Image Processing", Smith, Stephen M. and Brady, J. Michael
Author
Nizar Sallem
Definition at line 56 of file susan.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::ConstPtr = shared_ptr<const SUSANKeypoint<PointInT, PointOutT, NormalT, Intensity> >
Definition at line 60 of file susan.h.
KdTree
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::KdTree = typename Keypoint<PointInT, PointOutT>::KdTree
Definition at line 64 of file susan.h.
PointCloudIn
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::PointCloudIn = typename Keypoint<PointInT, PointOutT>::PointCloudIn
Definition at line 62 of file susan.h.
PointCloudInConstPtr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::PointCloudInConstPtr = typename PointCloudIn::ConstPtr
Definition at line 65 of file susan.h.
PointCloudN
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::PointCloudN = pcl::PointCloud<NormalT>
Definition at line 67 of file susan.h.
PointCloudNConstPtr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::PointCloudNConstPtr = typename PointCloudN::ConstPtr
Definition at line 69 of file susan.h.
PointCloudNPtr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::PointCloudNPtr = typename PointCloudN::Ptr
Definition at line 68 of file susan.h.
PointCloudOut
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::PointCloudOut = typename Keypoint<PointInT, PointOutT>::PointCloudOut
Definition at line 63 of file susan.h.
Ptr
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::Ptr = shared_ptr<SUSANKeypoint<PointInT, PointOutT, NormalT, IntensityT> >
Definition at line 59 of file susan.h.
Constructor & Destructor Documentation
SUSANKeypoint()
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::SUSANKeypoint (float radius = 0.01f, float distance_threshold = 0.001f, float angular_threshold = 0.0001f, float intensity_threshold = 7.0f) inline
Constructor.
Parameters
[in] radius the radius for normal estimation as well as for non maxima suppression
[in] distance_threshold to test if the nucleus is far enough from the centroid
[in] angular_threshold to test if normals are parallel
[in] intensity_threshold to test if points are of same color
Definition at line 88 of file susan.h.
References pcl::Keypoint< PointInT, PointOutT >::name_, and pcl::Keypoint< PointInT, PointOutT >::search_radius_.
~SUSANKeypoint()
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint () inline
Empty destructor.
Definition at line 106 of file susan.h.
References pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::detectKeypoints(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::initCompute(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::isWithinNucleusCentroid(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setAngularThreshold(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setDistanceThreshold(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setGeometricValidation(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setIntensityThreshold(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setNonMaxSupression(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setNormals(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setNumberOfThreads(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setRadius(), and pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setSearchSurface().
Member Function Documentation
detectKeypoints()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::detectKeypoints (PointCloudOut & output) override protected virtual
Abstract key point detection method.
Implements pcl::Keypoint< PointInT, PointOutT >.
Definition at line 303 of file susan.hpp.
References pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::isFinite(), pcl::PointCloud< PointT >::points, pcl::PointCloud< PointT >::push_back(), pcl::PointCloud< PointT >::reserve(), pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
initCompute()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > bool pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::initCompute () override protected virtual
Reimplemented from pcl::Keypoint< PointInT, PointOutT >.
Definition at line 215 of file susan.hpp.
References pcl::Feature< PointInT, PointOutT >::compute(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalEstimationMethod(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalSmoothingSize(), and pcl::Feature< PointInT, PointOutT >::setRadiusSearch().
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
isWithinNucleusCentroid()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > bool pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::isWithinNucleusCentroid (const Eigen::Vector3f & nucleus, const Eigen::Vector3f & centroid, const Eigen::Vector3f & nc, const PointInT & point) const protected
return true if a point lies within the line between the nucleus and the centroid
Parameters
[in] nucleus coordinate of the nucleus
[in] centroid of the SUSAN
[in] nc to centroid vector (used to speed up since it is constant for a given neighborhood)
[in] point the query point to test against
Returns
true if the point lies within [nucleus centroid]
Definition at line 255 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setAngularThreshold()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setAngularThreshold (float angular_threshold)
set the angular_threshold value for detecting corners.
Normals are considered as parallel if 1 - angular_threshold <= (Ni.Nj) <= 1
Parameters
[in] angular_threshold
Definition at line 75 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setDistanceThreshold()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setDistanceThreshold (float distance_threshold)
Definition at line 68 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setGeometricValidation()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setGeometricValidation (bool validate)
Filetr false positive using geometric criteria.
The nucleus and the centroid should at least distance_threshold_ from each other AND all the points belonging to the USAN must be within the segment [nucleus centroid].
Parameters
[in] validate
Definition at line 54 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setIntensityThreshold()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setIntensityThreshold (float intensity_threshold)
set the intensity_threshold value for detecting corners.
Parameters
[in] intensity_threshold
Definition at line 82 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setNonMaxSupression()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setNonMaxSupression (bool nonmax)
Apply non maxima suppression to the responses to keep strongest corners.
Note
in SUSAN points with less response or stronger corners
Definition at line 47 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setNormals()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setNormals (const PointCloudNConstPtr & normals)
set normals if precalculated normals are available.
Parameters
normals
Definition at line 89 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setNumberOfThreads()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setNumberOfThreads (unsigned int nr_threads)
Initialize the scheduler and set the number of threads to use.
Parameters
nr_threads the number of hardware threads to use (0 sets the value back to automatic)
Definition at line 104 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setRadius()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setRadius (float radius)
set the radius for normal estimation and non maxima supression.
Parameters
[in] radius
Definition at line 61 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
setSearchSurface()
template<typename PointInT , typename PointOutT , typename NormalT , typename IntensityT > void pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::setSearchSurface (const PointCloudInConstPtr & cloud) override virtual
Provide a pointer to the input dataset that we need to estimate features at every point for.
Parameters
cloud the const boost shared pointer to a PointCloud message
Reimplemented from pcl::Keypoint< PointInT, PointOutT >.
Definition at line 96 of file susan.hpp.
Referenced by pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::~SUSANKeypoint().
The documentation for this class was generated from the following files:
pcl/keypoints/susan.h
pcl/keypoints/impl/susan.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Sun Mar 8 2020 12:53:06