Point Cloud Library (PCL): pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT > Class Template Reference
pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT > Class Template Reference
Module keypoints
HarrisKeypoint2D detects Harris corners family points.
#include <pcl/keypoints/harris_2d.h>
Public Types
enum ResponseMethod { HARRIS = 1, NOBLE, LOWE, TOMASI }
using Ptr = shared_ptr< HarrisKeypoint2D< PointInT, PointOutT, IntensityT > >
using ConstPtr = shared_ptr< const HarrisKeypoint2D< PointInT, PointOutT, IntensityT > >
using PointCloudIn = typename Keypoint< PointInT, PointOutT >::PointCloudIn
using PointCloudOut = typename Keypoint< PointInT, PointOutT >::PointCloudOut
using KdTree = typename Keypoint< PointInT, PointOutT >::KdTree
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
Public Types inherited from pcl::Keypoint< PointInT, PointOutT >
using Ptr = shared_ptr< Keypoint< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Keypoint< PointInT, PointOutT > >
using BaseClass = PCLBase< PointInT >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(int, double, std::vector< int > &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, int index, double, std::vector< int > &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
HarrisKeypoint2D (ResponseMethod method=HARRIS, int window_width=3, int window_height=3, int min_distance=5, float threshold=0.0)
Constructor.
void setMethod (ResponseMethod type)
set the method of the response to be calculated.
void setWindowWidth (int window_width)
Set window width.
void setWindowHeight (int window_height)
Set window height.
void setSkippedPixels (int skipped_pixels)
Set number of pixels to skip.
void setMinimalDistance (int min_distance)
Set minimal distance between candidate keypoints.
void setThreshold (float threshold)
set the threshold value for detecting corners.
void setNonMaxSupression (bool=false)
whether non maxima suppression should be applied or the response for each point should be returned
void setRefine (bool do_refine)
whether the detected key points should be refined or not.
void setNumberOfThreads (unsigned int nr_threads=0)
Initialize the scheduler and set the number of threads to use.
Public Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
Keypoint ()
void harrisCorner (ImageType &output, ImageType &input, const float sigma_d, const float sigma_i, const float alpha, const float thresh)
void hessianBlob (ImageType &output, ImageType &input, const float sigma, bool SCALE)
void hessianBlob (ImageType &output, ImageType &input, const float start_scale, const float scaling_factor, const int num_scales)
void imageElementMultiply (ImageType &output, ImageType &input1, ImageType &input2)
Keypoint ()
Empty constructor.
~Keypoint ()
Empty destructor.
virtual void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to the input dataset that we need to estimate features at every point for.
PointCloudInConstPtr getSearchSurface ()
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod ()
Get a pointer to the search method used.
double getSearchParameter ()
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch ()
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the key point detection.
double getRadiusSearch ()
Get the sphere radius used for determining the neighbors.
pcl::PointIndicesConstPtr getKeypointsIndices ()
void compute (PointCloudOut &output)
Base method for key point detection for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
int searchForNeighbors (int index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute () override
void detectKeypoints (PointCloudOut &output) override
void responseHarris (PointCloudOut &output) const
gets the corner response for valid input points
void responseNoble (PointCloudOut &output) const
void responseLowe (PointCloudOut &output) const
void responseTomasi (PointCloudOut &output) const
void computeSecondMomentMatrix (std::size_t pos, float *coefficients) const
calculates the upper triangular part of unnormalized covariance matrix over intensities given by the 2D coordinates and window_width_ and window_height_
Protected Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual void detectKeypoints (PointCloudOut &output)=0
Abstract key point detection method.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
float threshold_
threshold for non maxima suppression
bool refine_
corner refinement
bool nonmax_
non maximas suppression
ResponseMethod method_
cornerness computation method
unsigned int threads_
number of threads to be used
Protected Attributes inherited from pcl::Keypoint< PointInT, PointOutT >
std::string name_
The key point detection method's name.
SearchMethod search_method_
The search method template for indices.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (casted from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
pcl::PointIndicesPtr keypoints_indices_
Indices of the keypoints in the input cloud.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT, typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>>
class pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >
HarrisKeypoint2D detects Harris corners family points.
Author
Nizar Sallem
Definition at line 53 of file harris_2d.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::ConstPtr = shared_ptr<const HarrisKeypoint2D<PointInT, PointOutT, IntensityT> >
Definition at line 57 of file harris_2d.h.
KdTree
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::KdTree = typename Keypoint<PointInT, PointOutT>::KdTree
Definition at line 61 of file harris_2d.h.
PointCloudIn
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::PointCloudIn = typename Keypoint<PointInT, PointOutT>::PointCloudIn
Definition at line 59 of file harris_2d.h.
PointCloudInConstPtr
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::PointCloudInConstPtr = typename PointCloudIn::ConstPtr
Definition at line 62 of file harris_2d.h.
PointCloudOut
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::PointCloudOut = typename Keypoint<PointInT, PointOutT>::PointCloudOut
Definition at line 60 of file harris_2d.h.
Ptr
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> using pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::Ptr = shared_ptr<HarrisKeypoint2D<PointInT, PointOutT, IntensityT> >
Definition at line 56 of file harris_2d.h.
Member Enumeration Documentation
ResponseMethod
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> enum pcl::HarrisKeypoint2D::ResponseMethod
Enumerator
HARRIS
NOBLE
LOWE
TOMASI
Definition at line 69 of file harris_2d.h.
Constructor & Destructor Documentation
HarrisKeypoint2D()
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D (ResponseMethod method = HARRIS, int window_width = 3, int window_height = 3, int min_distance = 5, float threshold = 0.0) inline
Constructor.
Parameters
[in] method the method to be used to determine the corner responses
window_width
window_height
min_distance
[in] threshold the threshold to filter out weak corners
Definition at line 78 of file harris_2d.h.
References pcl::Keypoint< PointInT, PointOutT >::name_, pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setMethod(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setMinimalDistance(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNonMaxSupression(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setRefine(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setSkippedPixels(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setThreshold(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setWindowHeight(), and pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setWindowWidth().
Member Function Documentation
computeSecondMomentMatrix()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::computeSecondMomentMatrix (std::size_t pos, float * coefficients) const protected
calculates the upper triangular part of unnormalized covariance matrix over intensities given by the 2D coordinates and window_width_ and window_height_
Definition at line 101 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
detectKeypoints()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::detectKeypoints (PointCloudOut & output) override protected
!! nsallem 20120220 : we don't test here for density so if one term in nan the result is nan
Definition at line 173 of file harris_2d.hpp.
References pcl::isFinite().
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
initCompute()
template<typename PointInT , typename PointOutT , typename IntensityT > bool pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::initCompute () override protected virtual
Reimplemented from pcl::Keypoint< PointInT, PointOutT >.
Definition at line 127 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
responseHarris()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseHarris (PointCloudOut & output) const protected
gets the corner response for valid input points
Definition at line 292 of file harris_2d.hpp.
References pcl::isFinite().
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
responseLowe()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseLowe (PointCloudOut & output) const protected
Definition at line 364 of file harris_2d.hpp.
References pcl::isFinite().
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
responseNoble()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseNoble (PointCloudOut & output) const protected
Definition at line 328 of file harris_2d.hpp.
References pcl::isFinite().
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
responseTomasi()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseTomasi (PointCloudOut & output) const protected
Definition at line 400 of file harris_2d.hpp.
References pcl::isFinite().
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
setMethod()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setMethod (ResponseMethod type)
set the method of the response to be calculated.
Parameters
[in] type
Definition at line 45 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setMinimalDistance()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setMinimalDistance (int min_distance)
Set minimal distance between candidate keypoints.
Definition at line 94 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setNonMaxSupression()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNonMaxSupression (bool nonmax = false)
whether non maxima suppression should be applied or the response for each point should be returned
Note
this value needs to be turned on in order to apply thresholding and refinement
Parameters
[in] nonmax default is false
Definition at line 66 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setNumberOfThreads()
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads (unsigned int nr_threads = 0) inline
Initialize the scheduler and set the number of threads to use.
Parameters
nr_threads the number of hardware threads to use (0 sets the value back to automatic)
Definition at line 133 of file harris_2d.h.
References pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::computeSecondMomentMatrix(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::detectKeypoints(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::initCompute(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseHarris(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseLowe(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseNoble(), pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::responseTomasi(), and pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::threads_.
setRefine()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setRefine (bool do_refine)
whether the detected key points should be refined or not.
If turned of, the key points are a subset of the original point cloud. Otherwise the key points may be arbitrary. note non maxima supression needs to be on in order to use this feature.
Parameters
[in] do_refine
Definition at line 59 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setSkippedPixels()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setSkippedPixels (int skipped_pixels)
Set number of pixels to skip.
Definition at line 87 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setThreshold()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setThreshold (float threshold)
set the threshold value for detecting corners.
This is only evaluated if non maxima suppression is turned on. note non maxima suppression needs to be activated in order to use this feature.
Parameters
[in] threshold
Definition at line 52 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setWindowHeight()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setWindowHeight (int window_height)
Set window height.
Definition at line 80 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
setWindowWidth()
template<typename PointInT , typename PointOutT , typename IntensityT > void pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setWindowWidth (int window_width)
Set window width.
Definition at line 73 of file harris_2d.hpp.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::HarrisKeypoint2D().
Member Data Documentation
method_
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> ResponseMethod pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::method_ protected
cornerness computation method
Definition at line 163 of file harris_2d.h.
nonmax_
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> bool pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::nonmax_ protected
non maximas suppression
Definition at line 161 of file harris_2d.h.
refine_
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> bool pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::refine_ protected
corner refinement
Definition at line 159 of file harris_2d.h.
threads_
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> unsigned int pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::threads_ protected
number of threads to be used
Definition at line 165 of file harris_2d.h.
Referenced by pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::setNumberOfThreads().
threshold_
template<typename PointInT , typename PointOutT , typename IntensityT = pcl::common::IntensityFieldAccessor<PointInT>> float pcl::HarrisKeypoint2D< PointInT, PointOutT, IntensityT >::threshold_ protected
threshold for non maxima suppression
Definition at line 157 of file harris_2d.h.
The documentation for this class was generated from the following files:
pcl/keypoints/harris_2d.h
pcl/keypoints/impl/harris_2d.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Sun Mar 8 2020 12:52:16