Point Cloud Library (PCL): pcl::search::KdTree< PointT, Tree > Class Template Reference
pcl::search::KdTree< PointT, Tree > Class Template Reference
Module search
search::KdTree is a wrapper class which inherits the pcl::KdTree class for performing search functions using KdTree structure.
#include <pcl/search/kdtree.h>
Public Types
using PointCloud = typename Search< PointT >::PointCloud
using PointCloudConstPtr = typename Search< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< KdTree< PointT, Tree > >
using ConstPtr = shared_ptr< const KdTree< PointT, Tree > >
using KdTreePtr = typename Tree::Ptr
using KdTreeConstPtr = typename Tree::ConstPtr
using PointRepresentationConstPtr = typename PointRepresentation< PointT >::ConstPtr
Public Types inherited from pcl::search::Search< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using Ptr = shared_ptr< pcl::search::Search< PointT > >
using ConstPtr = shared_ptr< const pcl::search::Search< PointT > >
using IndicesPtr = shared_ptr< std::vector< int > >
using IndicesConstPtr = shared_ptr< const std::vector< int > >
Public Member Functions
KdTree (bool sorted=true)
Constructor for KdTree.
~KdTree ()
Destructor for KdTree.
void setPointRepresentation (const PointRepresentationConstPtr &point_representation)
Provide a pointer to the point representation to use to convert points into k-D vectors.
PointRepresentationConstPtr getPointRepresentation () const
Get a pointer to the point representation used when converting points into k-D vectors.
void setSortedResults (bool sorted_results) override
Sets whether the results have to be sorted or not.
void setEpsilon (float eps)
Set the search epsilon precision (error bound) for nearest neighbors searches.
float getEpsilon () const
Get the search epsilon precision (error bound) for nearest neighbors searches.
void setInputCloud (const PointCloudConstPtr &cloud, const IndicesConstPtr &indices=IndicesConstPtr()) override
Provide a pointer to the input dataset.
int nearestKSearch (const PointT &point, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances) const override
Search for the k-nearest neighbors for the given query point.
int radiusSearch (const PointT &point, double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0) const override
Search for all the nearest neighbors of the query point in a given radius.
Public Member Functions inherited from pcl::search::Search< PointT >
Search (const std::string &name="", bool sorted=false)
Constructor.
virtual ~Search ()
Destructor.
virtual const std::string & getName () const
Returns the search method name.
virtual bool getSortedResults ()
Gets whether the results should be sorted (ascending in the distance) or not Otherwise the results may be returned in any order.
virtual void setInputCloud (const PointCloudConstPtr &cloud, const IndicesConstPtr &indices=IndicesConstPtr())
Pass the input dataset that the search will be performed on.
virtual PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
template<typename PointTDiff >
int nearestKSearchT (const PointTDiff &point, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances) const
Search for k-nearest neighbors for the given query point.
virtual int nearestKSearch (const PointCloud &cloud, int index, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances) const
Search for k-nearest neighbors for the given query point.
virtual int nearestKSearch (int index, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances) const
Search for k-nearest neighbors for the given query point (zero-copy).
virtual void nearestKSearch (const PointCloud &cloud, const std::vector< int > &indices, int k, std::vector< std::vector< int > > &k_indices, std::vector< std::vector< float > > &k_sqr_distances) const
Search for the k-nearest neighbors for the given query point.
template<typename PointTDiff >
void nearestKSearchT (const pcl::PointCloud< PointTDiff > &cloud, const std::vector< int > &indices, int k, std::vector< std::vector< int > > &k_indices, std::vector< std::vector< float > > &k_sqr_distances) const
Search for the k-nearest neighbors for the given query point.
template<typename PointTDiff >
int radiusSearchT (const PointTDiff &point, double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0) const
Search for all the nearest neighbors of the query point in a given radius.
virtual int radiusSearch (const PointCloud &cloud, int index, double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0) const
Search for all the nearest neighbors of the query point in a given radius.
virtual int radiusSearch (int index, double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0) const
Search for all the nearest neighbors of the query point in a given radius (zero-copy).
virtual void radiusSearch (const PointCloud &cloud, const std::vector< int > &indices, double radius, std::vector< std::vector< int > > &k_indices, std::vector< std::vector< float > > &k_sqr_distances, unsigned int max_nn=0) const
Search for all the nearest neighbors of the query point in a given radius.
template<typename PointTDiff >
void radiusSearchT (const pcl::PointCloud< PointTDiff > &cloud, const std::vector< int > &indices, double radius, std::vector< std::vector< int > > &k_indices, std::vector< std::vector< float > > &k_sqr_distances, unsigned int max_nn=0) const
Search for all the nearest neighbors of the query points in a given radius.
Protected Attributes
KdTreePtr tree_
A pointer to the internal KdTree object.
Protected Attributes inherited from pcl::search::Search< PointT >
PointCloudConstPtr input_
IndicesConstPtr indices_
bool sorted_results_
std::string name_
Additional Inherited Members
Protected Member Functions inherited from pcl::search::Search< PointT >
void sortResults (std::vector< int > &indices, std::vector< float > &distances) const
Detailed Description
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>>
class pcl::search::KdTree< PointT, Tree >
search::KdTree is a wrapper class which inherits the pcl::KdTree class for performing search functions using KdTree structure.
KdTree is a generic type of 3D spatial locator using kD-tree structures. The class is making use of the FLANN (Fast Library for Approximate Nearest Neighbor) project by Marius Muja and David Lowe.
Author
Radu B. Rusu
Definition at line 61 of file kdtree.h.
Member Typedef Documentation
ConstPtr
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::ConstPtr = shared_ptr<const KdTree<PointT, Tree> >
Definition at line 79 of file kdtree.h.
KdTreeConstPtr
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::KdTreeConstPtr = typename Tree::ConstPtr
Definition at line 82 of file kdtree.h.
KdTreePtr
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::KdTreePtr = typename Tree::Ptr
Definition at line 81 of file kdtree.h.
PointCloud
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::PointCloud = typename Search<PointT>::PointCloud
Definition at line 64 of file kdtree.h.
PointCloudConstPtr
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::PointCloudConstPtr = typename Search<PointT>::PointCloudConstPtr
Definition at line 65 of file kdtree.h.
PointRepresentationConstPtr
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::PointRepresentationConstPtr = typename PointRepresentation<PointT>::ConstPtr
Definition at line 83 of file kdtree.h.
Ptr
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> using pcl::search::KdTree< PointT, Tree >::Ptr = shared_ptr<KdTree<PointT, Tree> >
Definition at line 78 of file kdtree.h.
Constructor & Destructor Documentation
KdTree()
template<typename PointT , class Tree > pcl::search::KdTree< PointT, Tree >::KdTree (bool sorted = true)
Constructor for KdTree.
Parameters
[in] sorted set to true if the nearest neighbor search results need to be sorted in ascending order based on their distance to the query point
Definition at line 46 of file kdtree.hpp.
~KdTree()
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> pcl::search::KdTree< PointT, Tree >::~KdTree () inline
Destructor for KdTree.
Definition at line 96 of file kdtree.h.
Member Function Documentation
getEpsilon()
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> float pcl::search::KdTree< PointT, Tree >::getEpsilon () const inline
Get the search epsilon precision (error bound) for nearest neighbors searches.
Definition at line 127 of file kdtree.h.
getPointRepresentation()
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> PointRepresentationConstPtr pcl::search::KdTree< PointT, Tree >::getPointRepresentation () const inline
Get a pointer to the point representation used when converting points into k-D vectors.
Definition at line 108 of file kdtree.h.
nearestKSearch()
template<typename PointT, class Tree > int pcl::search::KdTree< PointT, Tree >::nearestKSearch (const PointT & point, int k, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances) const override virtual
Search for the k-nearest neighbors for the given query point.
Parameters
[in] point the given query point
[in] k the number of neighbors to search for
[out] k_indices the resultant indices of the neighboring points (must be resized to k a priori!)
[out] k_sqr_distances the resultant squared distances to the neighboring points (must be resized to k a priori!)
Returns
number of neighbors found
Implements pcl::search::Search< PointT >.
Definition at line 88 of file kdtree.hpp.
Referenced by pcl::GeneralizedIterativeClosestPoint< PointSource, PointTarget >::computeCovariances(), pcl::search::KdTree< SceneT >::getEpsilon(), pcl::getMeanPointDensity(), and pcl::SupervoxelClustering< PointT >::refineSupervoxels().
radiusSearch()
template<typename PointT, class Tree > int pcl::search::KdTree< PointT, Tree >::radiusSearch (const PointT & point, double radius, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances, unsigned int max_nn = 0) const override virtual
Search for all the nearest neighbors of the query point in a given radius.
Parameters
[in] point the given query point
[in] radius the radius of the sphere bounding all of p_q's neighbors
[out] k_indices the resultant indices of the neighboring points
[out] k_sqr_distances the resultant squared distances to the neighboring points
[in] max_nn if given, bounds the maximum returned neighbors to this value. If max_nn is set to 0 or to a number higher than the number of points in the input cloud, all neighbors in radius will be returned.
Returns
number of neighbors found in radius
Implements pcl::search::Search< PointT >.
Definition at line 97 of file kdtree.hpp.
Referenced by pcl::search::KdTree< SceneT >::getEpsilon(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::refineCorners(), and pcl::SupervoxelClustering< PointT >::refineSupervoxels().
setEpsilon()
template<typename PointT , class Tree > void pcl::search::KdTree< PointT, Tree >::setEpsilon (float eps)
Set the search epsilon precision (error bound) for nearest neighbors searches.
Parameters
[in] eps precision (error bound) for nearest neighbors searches
Definition at line 70 of file kdtree.hpp.
Referenced by pcl::search::KdTree< SceneT >::getPointRepresentation().
setInputCloud()
template<typename PointT , class Tree > void pcl::search::KdTree< PointT, Tree >::setInputCloud (const PointCloudConstPtr & cloud, const IndicesConstPtr & indices = IndicesConstPtr ()) override
Provide a pointer to the input dataset.
Parameters
[in] cloud the const boost shared pointer to a PointCloud message
[in] indices the point indices subset that is to be used from cloud
Definition at line 77 of file kdtree.hpp.
Referenced by pcl::people::GroundBasedPeopleDetectionApp< PointT >::compute(), pcl::search::KdTree< SceneT >::getEpsilon(), pcl::getMeanPointDensity(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::refineCorners(), pcl::SupervoxelClustering< PointT >::refineSupervoxels(), pcl::CPCSegmentation< PointT >::segment(), pcl::HypothesisVerification< ModelT, SceneT >::setSceneCloud(), and pcl::GlobalHypothesesVerification< ModelT, SceneT >::verify().
setPointRepresentation()
template<typename PointT , class Tree > void pcl::search::KdTree< PointT, Tree >::setPointRepresentation (const PointRepresentationConstPtr & point_representation)
Provide a pointer to the point representation to use to convert points into k-D vectors.
Parameters
[in] point_representation the const boost shared pointer to a PointRepresentation
Definition at line 54 of file kdtree.hpp.
Referenced by pcl::search::KdTree< SceneT >::~KdTree().
setSortedResults()
template<typename PointT , class Tree > void pcl::search::KdTree< PointT, Tree >::setSortedResults (bool sorted_results) override virtual
Sets whether the results have to be sorted or not.
Parameters
[in] sorted_results set to true if the radius search results should be sorted
Reimplemented from pcl::search::Search< PointT >.
Definition at line 62 of file kdtree.hpp.
Referenced by pcl::search::KdTree< SceneT >::getPointRepresentation().
Member Data Documentation
tree_
template<typename PointT, class Tree = pcl::KdTreeFLANN<PointT>> KdTreePtr pcl::search::KdTree< PointT, Tree >::tree_ protected
A pointer to the internal KdTree object.
Definition at line 170 of file kdtree.h.
Referenced by pcl::search::KdTree< SceneT >::getEpsilon(), and pcl::search::KdTree< SceneT >::getPointRepresentation().
The documentation for this class was generated from the following files:
pcl/search/kdtree.h
pcl/search/impl/kdtree.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Sun Mar 8 2020 12:54:13