Point Cloud Library (PCL): pcl::poisson::UpSampleData Struct Reference
pcl::poisson::UpSampleData Struct Reference
#include <pcl/surface/3rdparty/poisson4/multi_grid_octree_data.hpp>
Public Member Functions
UpSampleData (void)
UpSampleData (int s, double v1, double v2)
Public Attributes
int start
double v [2]
Detailed Description
Definition at line 1493 of file multi_grid_octree_data.hpp.
Constructor & Destructor Documentation
UpSampleData() [1/2]
pcl::poisson::UpSampleData::UpSampleData (void) inline
Definition at line 1497 of file multi_grid_octree_data.hpp.
UpSampleData() [2/2]
pcl::poisson::UpSampleData::UpSampleData (int s, double v1, double v2) inline
Definition at line 1498 of file multi_grid_octree_data.hpp.
References pcl::poisson::BinaryNode< Real >::CenterIndex(), pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::TreeNodeData::constraint, pcl::poisson::OctNode< NodeData, Real >::depth(), pcl::poisson::OctNode< NodeData, Real >::depthAndOffset(), pcl::poisson::Cube::FactorCornerIndex(), pcl::poisson::OctNode< NodeData, Real >::Neighbors3::neighbors, pcl::poisson::OctNode< NodeData, Real >::NeighborKey3::neighbors, pcl::poisson::SortedTreeNodes::nodeCount, pcl::poisson::OctNode< NodeData, Real >::nodeData, pcl::poisson::TreeNodeData::nodeIndex, pcl::poisson::OctNode< NodeData, Real >::parent, pcl::poisson::TreeNodeData::pointIndex, pcl::poisson::Vector< T >::Resize(), pcl::poisson::SparseMatrix< T >::Resize(), pcl::poisson::SparseMatrix< T >::rowSizes, pcl::poisson::SparseMatrix< T >::SetRowSize(), pcl::poisson::TreeNodeData::solution, start, pcl::poisson::SortedTreeNodes::treeNodes, and v.
Member Data Documentation
start
int pcl::poisson::UpSampleData::start
Definition at line 1495 of file multi_grid_octree_data.hpp.
Referenced by UpSampleData().
v
double pcl::poisson::UpSampleData::v[2]
Definition at line 1496 of file multi_grid_octree_data.hpp.
Referenced by UpSampleData().
The documentation for this struct was generated from the following file:
pcl/surface/3rdparty/poisson4/multi_grid_octree_data.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Sun Mar 8 2020 12:53:58